<?php

namespace BackBundle\Repository;

/**
 * Agenda_LaboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Agenda_LaboRepository extends \Doctrine\ORM\EntityRepository
{
}
