<?php

namespace BackBundle\Repository;

/**
 * Agenda_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Agenda_evenementRepository extends \Doctrine\ORM\EntityRepository
{
}
