<?php

namespace BackBundle\Repository;

/**
 * AgendaLaboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaLaboRepository extends \Doctrine\ORM\EntityRepository
{
}
