<?php

namespace BackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findLimitedOrderedByDateDebut($limit = 3, $offset = 0){
        return $this->getEntityManager()
            ->createQuery('SELECT e FROM BackBundle:Thing e ORDER BY e.dateDebut DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getResult();
    }
}
