<?php

namespace BackBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMySearch($data)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->where('c.decision = :maRecherche')
                ->setParameter('maRecherche', $data['maRecherche'])
            ->orWhere('c.classement = :classement')
                ->setParameter('classement', $data['classement'])
            ->orWhere('c.promotion = :promo')
                ->setParameter('promo', $data['promo'])
                ;


        return  $qb->getQuery()->getResult();
    }
}
