<?php

namespace BackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatsRepository extends EntityRepository
{
}
