<?php

namespace BackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RpresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RpresseRepository extends EntityRepository
{
}
