back_user:
    resource: "@BackBundle/Controller/UserController.php"
    type:     annotation

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /admin

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

agenda:
    resource: "@BackBundle/Controller/AgendaController.php"
    type:     annotation
    prefix:   /admin

user:
    resource: "@BackBundle/Controller/AgendaController.php"
    type:     annotation
    prefix:   /admin

document:
    resource: "@BackBundle/Controller/DocumentController.php"
    type:     annotation
    prefix:   /document

candidat:
    resource: "@BackBundle/Controller/CandidatController.php"
    type:     annotation
    prefix:   /candidat

jurylist:
    resource: "@BackBundle/Controller/JuryController.php"
    type:     annotation
    prefix:   /jurylist


article:
    resource: "@BlogBundle/Controller/ArticleController.php"
    type:     annotation
    prefix:   /blog

rpresse:
    resource: "@BackBundle/Controller/RpresseController.php"
    type:     annotation
    prefix:   /admin

vote:
    resource: "@BackBundle/Controller/VoteController.php"
    type:     annotation
    prefix:   /jury

backjury:
    resource: "@BackBundle/Controller/BackJuryController.php"
    type:     annotation
    prefix:   /jury

backpartenaire:
    resource: "@BackBundle/Controller/BackPartenaireController.php"
    type:     annotation
    prefix:   /partenaire

backisipca:
    resource: "@BackBundle/Controller/BackIsipcaController.php"
    type:     annotation
    prefix:   /isipca

newpartenaire:
    resource: "@BackBundle/Controller/PartenaireController.php"
    type:     annotation
    prefix:   /partenairenew

newisipca:
    resource: "@BackBundle/Controller/Agenda_LaboController.php"
    type:     annotation
    prefix:   /isipcanew

translation:
    path:     /traduction
    defaults: { _controller: FrontBundle:Default:translation }

