back_presentation:
    resource: "@BackBundle/Controller/PresentationController.php"
    type:     annotation

back_user:
    resource: "@BackBundle/Controller/UserController.php"
    type:     annotation

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/blog

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}


#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#    prefix: /{_locale}
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

agenda:
    resource: "@BackBundle/Controller/AgendaController.php"
    type:     annotation
    prefix:   /{_locale}/admin

user:
    resource: "@BackBundle/Controller/AgendaController.php"
    type:     annotation
    prefix:   /admin

document:
    resource: "@BackBundle/Controller/DocumentController.php"
    type:     annotation
    prefix:   /{_locale}/document

candidat:
    resource: "@BackBundle/Controller/CandidatController.php"
    type:     annotation
    prefix:   /{_locale}/candidat

jurylist:
    resource: "@BackBundle/Controller/JuryController.php"
    type:     annotation
    prefix:   /{_locale}/jurylist

commentaire:
    resource: "@BlogBundle/Controller/CommentaireController.php"
    type:     annotation
    prefix:   /admin

article:
    resource: "@BlogBundle/Controller/ArticleController.php"
    type:     annotation
    prefix:   /{_locale}/blog

rpresse:
    resource: "@BackBundle/Controller/RpresseController.php"
    type:     annotation
    prefix:   /{_locale}/admin

vote:
    resource: "@BackBundle/Controller/VoteController.php"
    type:     annotation
    prefix:   /{_locale}/jury

backjury:
    resource: "@BackBundle/Controller/BackJuryController.php"
    type:     annotation
    prefix:   /{_locale}/jury

backpartenaire:
    resource: "@BackBundle/Controller/BackPartenaireController.php"
    type:     annotation
    prefix:   /{_locale}/partenaire

backisipca:
    resource: "@BackBundle/Controller/BackIsipcaController.php"
    type:     annotation
    prefix:   /{_locale}/isipca

newpartenaire:
    resource: "@BackBundle/Controller/PartenaireController.php"
    type:     annotation
    prefix:   /{_locale}/partenairenew

newisipca:
    resource: "@BackBundle/Controller/Agenda_LaboController.php"
    type:     annotation
    prefix:   /{_locale}/isipcanew


