<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getCommentaires($id)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('id = :id')
            ->setParameter('id', $id)
            ->leftJoin('a.commentaires', 'c')
            ->orderBy('c.date', 'DESC')
            ;

        return $qb->getQuery()
            ->getResult();
    }
}
