<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findByOrderArticle($data) {

        $qb = $this->createQueryBuilder('a')
            ->where('a.date = :article')
                ->setParameter('a.article', $data['date'])
            ->orderBy('a.date', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }
}
